### PR TITLE
api: add missing ids and tags

### PR DESCRIPTION
**Pull request by lzap**
I noticed that some of the endpoints are missing ids. To further improve generated output from HTML/JS generator, this patch adds tags which improves the redocly generator.

This is a portion of https://github.com/osbuild/image-builder/pull/900

### CODE REVIEW

**Comment by bcl** [comment]
I think you need to rerun the generator. Also, #900 links to #839 which has the original problem description :) Could you make the this commit message a little more verbose?

**Comment by lzap** [comment]
Thanks, improved the PR description.

**Comment by lzap** [comment]
Is there any chance to get this in? I stripped this down to the barebones. All I want is the link in the README which I find quite useful and better navigation which the tags do bring. Thanks.

**Review by ezr-ondrej — APPROVED** [review]
This looks pretty reasonable to me and no real change, so it should  not break stuff :)

**Pull request merged**
