### PR TITLE
Export endpoint followup

### PR DESCRIPTION
**Pull request by avitova**
I have done some changes for the purpose of testing the metadata field. We do not use the metadata in the handler yet, because it is IMO not needed.

### CODE REVIEW

**Review by ezr-ondrej — DISMISSED** [review]
I agree we do not need it in handler, but populate the entry from DB properly is for sure a good thing to have - it could have confused ppl in future :+1:

**Comment by ezr-ondrej** [comment]
It conflicts - prolly with my PR, sorry! :disappointed:

**Comment by avitova** [comment]
Rebased :heavy_check_mark:

**Comment by lzap** [comment]
LGTM please rebase red CI.

**Review by ezr-ondrej — APPROVED** [review]
Thanks! :orange_heart:

**Comment by lzap** [comment]
Let’s see now.

**Pull request merged**
